# Use root/example as user/password credentials
##The compose just starts a sql container.
version: '3.1'

services:
  db:
   image: mysql:5.7
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD=matheus
     - MYSQL_DATABASE=hireme